### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by 4hbane** [HouariZegai/FXMailer#1]
## Suggestions

- What if we actually can replace the **TO** section to many inputs depending on how much persons we can send the email to; and then show just the input fields and behind ( backend ) we can parse that and create the JSON Array.  This will help the users who are not very familiar with JSON annotations.

- Same thing in the **body** section.

**Comment by HouariZegai** [comment]
Hello Abdellah,
Good suggestion, the reason I made Json is to simplify the process for the tool users, but we don't take into consideration the persons who do not know JSON.
Maybe we add multi-choice for users (JSON, Input fields, ...).

Thanks a lot!

**Comment by 4hbane** [comment]
Yeah I see, Good job 👏
